Fixing #607 + Refactoring
JohnnyCrazy/SpotifyAPI-NET pull request #608
Opened 2021-05-07 09:04 UTC by p-bojkowski

Added me/episodes and done some refactoring

2021-05-09 09:03 UTC, JohnnyCrazy approved these changes
Looks good except those 2 things, thank you! 👍🏼

2021-05-09 09:04 UTC, JohnnyCrazy requested changes
^request changes

2021-05-10 06:48 UTC, p-bojkowski commented on SpotifyAPI.Web/SpotifyUrls.cs.bak
> +using System;
yes

2021-05-10 08:42 UTC, JohnnyCrazy requested changes
Found two more small things, I think then we should be good to go! 👍🏼

2021-05-10 08:42 UTC, JohnnyCrazy commented on SpotifyAPI.Web/Models/Request/LibrarySaveEpisodesRequest.cs
> +    public IList<string> URIs { get; }
I think this should be `ids` instead of `uris`. See: https://developer.spotify.com/documentation/web-api/reference/#endpoint-save-episodes-user

2021-05-10 08:42 UTC, JohnnyCrazy commented on SpotifyAPI.Web/Models/Request/LibraryEpisodesRequest.cs
> +  {
The parameter `market` is missing here, see https://developer.spotify.com/documentation/web-api/reference/#endpoint-get-users-saved-episodes

2021-06-14 12:57 UTC, p-bojkowski commented
@JohnnyCrazy should be OK now :) Sorry for the delay!

2021-06-20 18:49 UTC, JohnnyCrazy commented
Looks good! I will have one more detailed look and run some tests this week :)

No worries regarding the delay, I'm happy you contributed! 👍🏼

2021-08-10 20:17 UTC, JohnnyCrazy commented
Sorry for the delay here, looks very good! Thank you for your contribution 🙏 👍🏼

2021-08-10 20:17 UTC, merged